### ISSUE TITLE
cy.scrollIntoView() can only be used to scroll to 1 element, you tried to scroll to 2 elements.

### ISSUE THREAD

**Issue by alexlazarciuc** [avallete/cypress-nhover#47]
I am getting the mentioned error when trying to hover an element which will show a dropdown list menu.
My css is: [data-testid=user-menu]
Steps to replicate - navigate to ding.com
Register an account
Perform a hover action for My Account label in the header.

**Comment by alexlazarciuc** [comment]
Closing as we find out from where the problem was coming, I was using a locator which was not the parent. Thanks

**Comment by markpalfreeman** [comment]
@alexlazarciuc I know it's been a few months, but do you recall how you got to the bottom of this?
I'm running into the same error (not using this library) and it's not clear how a `cy.get(@alias).scrollIntoView()` would be returning 2 elements...

**Comment by Rebaiahmed** [comment]
Any update about this issue?

**Comment by sudikshabatra** [comment]
Any update?

**Comment by TahirMehmood8082** [comment]
still this issue arises in my code cypress 13.6.2

**Comment by titudatta11370** [comment]
Same here

**Comment by ljupcho46** [comment]
I noticed Cypress is making that same issue when I try to scrollintoview an element with children. So if the parent has three children, Cypress will throw an error saying you're trying to scroll to 4 elements at once. I don't understand why would this be an issue, but at least you can target one of the children as a workaround, until Cypress ppl decide to fix it.
